# Generated by Django 3.2 on 2021-05-04 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='marketList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='stockList',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=50)),
                ('last_update', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='stockInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('diff', models.FloatField()),
                ('volume', models.FloatField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockcode', to='stock.stocklist')),
            ],
        ),
        migrations.CreateModel(
            name='marketInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('score', models.FloatField()),
                ('tradingVolume', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.marketlist')),
            ],
        ),
    ]
