# Generated by Django 3.2 on 2021-06-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockx000500',
            name='pbr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockx000500',
            name='per',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockx000500',
            name='psr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockx000500',
            name='roa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockx000500',
            name='roe',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
