# Generated by Django 3.2 on 2021-06-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_backtestinfo_comparemonth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compare3Month',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('stockcode', models.CharField(max_length=10)),
                ('company', models.CharField(max_length=50)),
                ('gap', models.FloatField()),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='CompareMonth',
        ),
    ]
