# Generated by Django 3.2 on 2021-06-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20210613_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopStockHigh',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('stockcode', models.CharField(max_length=10)),
                ('company', models.CharField(max_length=50)),
                ('high', models.FloatField(blank=True, null=True)),
                ('gap', models.FloatField()),
                ('rank', models.IntegerField()),
            ],
        ),
    ]
