# Generated by Django 3.2 on 2021-06-15 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_topstockhigh'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackTestInfo',
        ),
    ]
