# Generated by Django 3.2 on 2021-06-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_delete_backtestinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopStockCap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('rank', models.IntegerField()),
                ('stockcode', models.CharField(max_length=10)),
                ('company', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('gap', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TopStockPrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('rank', models.IntegerField()),
                ('stockcode', models.CharField(max_length=10)),
                ('company', models.CharField(max_length=50)),
                ('todayPrice', models.FloatField()),
                ('gap', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='TopStockHigh',
        ),
    ]
