# Generated by Django 3.2 on 2021-06-16 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20210616_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topstockcap',
            old_name='price',
            new_name='todayPrice',
        ),
    ]
