# Generated by Django 3.2 on 2021-06-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_rename_price_topstockcap_todayprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackTestInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('date', models.DateTimeField(blank=True)),
                ('filename', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
