# Generated by Django 3.2 on 2021-06-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_alter_backtestinfo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtestinfo',
            name='date',
            field=models.DateField(),
        ),
    ]
