# Generated by Django 3.2 on 2021-06-07 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='companyData',
        ),
        migrations.DeleteModel(
            name='fmkorData',
        ),
    ]
