# Generated by Django 3.1.7 on 2021-04-29 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_account'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='account',
            new_name='accountData',
        ),
    ]
