# Generated by Django 3.1.7 on 2021-04-29 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_auto_20210429_1236'),
    ]

    operations = [
        migrations.DeleteModel(
            name='accountData',
        ),
    ]
